package lox;

public enum TokenType {
	// Single-character tokens
	LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, COMMA, DOT, MINUS, SLASH, STAR, PLUS, SEMICOLON,

	// Unary or binary tokens
	BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,

	// Literals
	IDENTIFIER, STRING, NUMBER, TRUE, FALSE, NIL,

	// Keywords
	AND, CLASS, ELSE, EXIT, FUN, FOR, IF, INSTANCE_OF, OR, PRINT, RETURN, SUPER, VAR, XOR, WHILE, THIS, BREAK, CONTINUE,

	// Others
	EOF, QUESTION_MARK, COLON
}
